import json
import urllib.request


# ============================================================
# TABBY CATS CONFIGURATION
# ============================================================


# ------------------------------------------------------------
# PET TYPE
# ------------------------------------------------------------
#
# The normal Tabby Cat:
#
#   PET_SKU       = "cat_tabbycat"
#   PET_TYPE      = "cat"
#   PET_TYPE_NAME = "Cat"
#
# Other animals can be configured here once their exact
# petType values are known.
# ------------------------------------------------------------

PET_SKU = "cat_tabbycat"
PET_TYPE = "cat"
PET_TYPE_NAME = "Cat"


# ------------------------------------------------------------
# NAME
# ------------------------------------------------------------

# First name.
FIRST_NAME = "Rainbow"

# Last name.
LAST_NAME = "Cat"


# ------------------------------------------------------------
# SPECIAL / LEGENDARY
# ------------------------------------------------------------
#
# This is NOT automatically determined by the name when we
# construct the snapshot manually.
#
# The site uses this value as a CSS class on the background.
#
# Known special values:
#
#   "Casper"
#   "Night"
#   "Pinky"
#   "Evil"
#   "Rainbow"
#   "Space"
#   "Tiny"
#   "Lil-404"
#
# Use None for a normal pet.
#
# Note:
# The name does not have to match the special value. For
# example, you can technically have:
#
#   FIRST_NAME = "Plasmadmin"
#   LAST_NAME = "Cat"
#   SPECIAL = "Rainbow"
#
# and the resulting snapshot will have Rainbow's special
# appearance while still being named Plasmadmin Cat.
# ------------------------------------------------------------

SPECIAL = "Rainbow"


# ------------------------------------------------------------
# COLOR
# ------------------------------------------------------------
#
# Known normal cat colors:
#
#   "orange"
#   "white"
#   "gray"
#   "black"
#   "brown"
#
# Other animals may have different valid colors.
# ------------------------------------------------------------

COLOR = "black"


# ------------------------------------------------------------
# BODY
# ------------------------------------------------------------
#
# Normal Tabby Cat values generated by the current game:
#
#   0
#   1
#   2
#   3
#   4
#   5
#
# Other animals may use different ranges.
# ------------------------------------------------------------

BODY = 0


# ------------------------------------------------------------
# HEAD
# ------------------------------------------------------------
#
# Normal Tabby Cat values generated by the current game:
#
#   0
#   1
#
# Other animals may use different values.
# ------------------------------------------------------------

HEAD = 0


# ------------------------------------------------------------
# LIKES PETS
# ------------------------------------------------------------
#
# Valid values:
#
#   "likes"
#   "hates"
# ------------------------------------------------------------

LIKES_PETS = "likes"


# ------------------------------------------------------------
# BACKGROUND COLOR
# ------------------------------------------------------------
#
# Known background colors:
#
#   "light-blue"
#   "red"
#   "blue"
#   "light-purple"
#   "purple"
#   "green"
#   "teal"
#   "yellow"
#   "mauve"
# ------------------------------------------------------------

BG_COLOR = "light-blue"


# ------------------------------------------------------------
# TOY
# ------------------------------------------------------------
#
# Use None for no toy.
#
# Known toy IDs:
#
#   "toy-Yarn"
#   "toy-Mouse"
#   "toy-Pizza"
#   "toy-Fishbones"
#   "toy-SoccerBall"
#   "toy-Donut"
#   "toy-Fishbowl"
#   "toy-Campfire"
#   "toy-MagicWand"
#   "toy-IceCream"
#   "toy-Coffee"
#   "toy-MiniGolf"
#   "toy-Flamingo"
#   "toy-Rocketship"
#   "toy-FoamFinger"
#   "toy-BonsaiTree"
#   "toy-Wine"
#   "toy-Synth"
#   "toy-Martini"
# ------------------------------------------------------------

TOY = None


# ------------------------------------------------------------
# GLASSES
# ------------------------------------------------------------
#
# Use None for no glasses.
#
# Known glasses IDs:
#
#   "glasses-Raybans"
#   "glasses-CatEye"
#   "glasses-ThreeD"
#   "glasses-OldMan"
#   "glasses-Scuba"
#   "glasses-Kerry"
#   "glasses-Blue"
#   "glasses-Sunglasses"
# ------------------------------------------------------------

GLASSES = None


# ------------------------------------------------------------
# HAT
# ------------------------------------------------------------
#
# Use None for no hat.
#
# Known hat IDs:
#
#   "hat-PartyHat"
#   "hat-Fedora"
#   "hat-Fez"
#   "hat-Chef"
#   "hat-Baseball"
#   "hat-Beanie"
#   "hat-Princess"
#   "hat-King"
#   "hat-Unicorn"
#   "hat-Sweatband"
#   "hat-Spinner"
#   "hat-Bow"
# ------------------------------------------------------------

HAT = None


# ------------------------------------------------------------
# KITTEN
# ------------------------------------------------------------
#
# Use None for no kitten.
#
# Known values:
#
#   "Frisky"
#   "Scuba"
#   "Unicorn"
#   "Camper"
#   "Rocketship"
#   "Fan"
#   "Bonsai"
#   "Midi"
#   "Athlete"
#   "Coffee"
#   "Chef"
#   "Birthday"
#
# These normally result from particular toy/hat/glasses
# combinations.
# ------------------------------------------------------------

KITTEN = None


# ============================================================
# BUILD SNAPSHOT DATA
# ============================================================

payload = {
    "petType": {
        "sku": PET_SKU,
        "type": PET_TYPE,
        "name": PET_TYPE_NAME,
    },

    "name": {
        "first": FIRST_NAME,
        "last": LAST_NAME,
        "full": f"{FIRST_NAME} {LAST_NAME}",
        "special": SPECIAL,
    },

    "color": COLOR,
    "likesPets": LIKES_PETS,
    "body": BODY,
    "head": HEAD,
    "bgColor": BG_COLOR,

    "kitten": KITTEN,
    "hat": HAT,
    "glasses": GLASSES,
    "toy": TOY,
}


# ============================================================
# SEND TO SERVER
# ============================================================

data = json.dumps(payload).encode("utf-8")

request = urllib.request.Request(
    "https://tabbycats.club/save",
    data=data,
    headers={
        "Content-Type": "application/json",
    },
    method="POST",
)


with urllib.request.urlopen(request) as response:
    snapshot_id = response.read().decode("utf-8").strip()


# ============================================================
# PRINT PERMALINK
# ============================================================

permalink = f"https://tabbycats.club/cat/{snapshot_id}"

print(permalink)